<?xml version="1.0"?>
<package format="3">
  <name>iri_people_tracking_mht</name>
  <version>1.0.0</version>
  <description>
    ROS2 wrapper of the people_tracking_mht C++ driver library, to track people detections.
  </description>

  <!-- Maintainer -->
  <maintainer email="erepiso@iri.upc.edu">Ely Repiso</maintainer>

  <!-- License -->
  <license>LGPL</license>

  <!-- Author -->
  <author email="erepiso@iri.upc.edu">Ely Repiso</author>

  <!-- Dependencies for building -->
  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- Dependencies required to build and run -->
  <build_depend>iri_base_algorithm</build_depend>
  <build_depend>iri_perception_msgs</build_depend>
  <build_depend>visualization_msgs</build_depend>
  <build_depend>tf2</build_depend>
  <build_depend>tf2_ros</build_depend>
  <build_depend>tf2_geometry_msgs</build_depend>
  <build_depend>rclcpp</build_depend>
  <build_depend>nav_msgs</build_depend>
  <build_depend>people_tracking_mht</build_depend>
  <build_depend>tf2_geometry_msgs</build_depend>
  <build_depend>iri_laser_people_detection</build_depend>
  <build_depend>iri_laser_people_map_filter</build_depend>
  
  <!-- Optional execution dependencies -->
  <!-- You may need to port these packages to ROS2 if they aren't available yet -->
  <exec_depend>rclcpp</exec_depend>
  <exec_depend>iri_base_algorithm</exec_depend>
  <exec_depend>nav_msgs</exec_depend>
  <exec_depend>visualization_msgs</exec_depend>
  <exec_depend>iri_perception_msgs</exec_depend>
  <exec_depend>tf2</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>tf2_geometry_msgs</exec_depend>
  <exec_depend>iri_base_algorithm</exec_depend>
  <exec_depend>people_tracking_mht</exec_depend>
  <exec_depend>iri_laser_people_detection</exec_depend>
  <exec_depend>iri_laser_people_map_filter</exec_depend>

  <!-- Export section -->
  <export>
    <!-- Information required for building against this package -->
    <build_type>ament_cmake</build_type>
  </export>
</package>
