frame_id:               "map"
local_tracker:          False
association_threshold:  2.0
confirmation_threshold: 0.9
deletion_threshold:     0.4
laser_probability:      0.9
laser_false_alarm:      0.1
laser_new_track:        0.11
laser_no_detection:     0.99
laser_no_confirmed:     0.02
laser_no_confirmed_iteration: 0.01
augment_covariance_track:     0.15
id_markers:           True
vel_markers:          True
cov_markers:          True
covdet_markers:       False
covpred_markers:      False
clust_markers:        False
cov_markers_head:     False
cov_markers_arm1:     False
cov_markers_arm2:     False
track_path_markers:   False 
mht_velocity_margin:  0.5 